# Generated by Django 2.2.9 on 2020-01-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em:'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='birth',
            field=models.DateTimeField(verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em:'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='genre',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='telephone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
    ]
