# Generated by Django 2.2.9 on 2020-01-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200127_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='dt_update',
            new_name='last_update',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, verbose_name='Gênero'),
        ),
    ]
